package modelo;

public enum CambiosModelo {
		CAMBIO_PUNTOS_MAXIMOS, 
		CAMBIO_LISTA_JUGADORES, 
		TIEMPO_TERMINO,
		MOSTRAR_PUNTAJE,
		MOSTRAR_PALABRAS,	
		CAMBIO_PUNTOS, 
		CAMBIO_PUNTOS_RONDA, 
		CAMBIO_ESTADO, 
		MOSTRAR_GANADOR, CAMBIO_JUGADOR, JUGADOR_PERDIO, DADOS_TIRADO, PALABRAS_VALIDAS, CAMBIO_TIEMPO, JUGADOR_SALIO,
	
}
